### ISSUE TITLE
bugs.ruby-lang.org generates emails which fail DMARC

### ISSUE THREAD

**Issue by jikamens** [ruby/b.r-l.o#91] opened 2018-06-27 20:34 UTC
Hi,

We are getting ready to enable [DMARC](https://dmarc.org/) enforcement on our email domain, which means that we are currently monitoring for messages that purport to come from our domain that are not DMARC compliant.

Through that monitoring, we discovered that bugs.ruby-lang.org sends out emails purporting to be from the people submitting bugs to the site. Those emails violate DMARC, and therefore will likely be rejected by more and more sites as p=reject or p=quarantine DMARC policies become more and more common.

Bugs.ruby-lang.org should not be generating emails claiming to be from senders that bugs.ruby-lang.org is not actually authorized to be sending email as.

I first reported this to the maintainers of Redmine at https://www.redmine.org/issues/29028, but as they point out [there](https://www.redmine.org/issues/29028#note-4), this is actually a customization that is [specific to bugs.ruby-lang.org](https://github.com/ruby/redmine_ruby_lang_mailing_list_customization/blob/master/lib/redmine_ruby_lang_mailing_list_customization/redmine_ext/mailer.rb#L4).

**Comment by ahorek** [comment] 2020-08-14 01:02
we could change "from" header to "reply_to" header, at least for mailing lists. In order to comply the rules, from sender has to be a domain which is allowed like notifications@ruby-lang.org. That will unfortunatelly change the name of a sender displayed in your mail client.

**Comment by hanazuki** [comment] 2021-06-01 02:56
Hi @hsbt, any updates on this issue? (and anything I can help with?)

More companies are moving to implement the DMARC "reject" policy these days, and emails from Ruby contributors who use their work email address are now classified as Junks by my mailbox provider. Such domains include google.com, datadoghq.com, shopify.com, and yahoo.com (in a random order as I remember). This isn't very pleasant to me, and I would be happy if we could patch the situation.

**Comment by hsbt** [comment] 2021-06-01 02:58
@hanazuki We use sendgrid for delivering email from bugs.ruby-lang.org. Do you know the DMARC configuration with sendgrid?

**Comment by hanazuki** [comment] 2021-06-01 03:59
The problem is not caused by the email delivery service but by Redmine, which generates emails "spoofing" sender addresses (header from).

I think https://github.com/ruby/b.r-l.o/issues/91#issuecomment-673782367 (to change From header value to some address with the domain name under our control, say ruby-lang.org) is the right way to go.
And also, we have to update the domain's SPF record to allow SendGrid to send emails using that domain for alignment with our own DMARC policy.

[SendGrid can sign outgoing emails with DKIM signature](https://sendgrid.com/docs/ui/account-and-settings/how-to-set-up-domain-authentication/) to prevent somebody else from spoofing our domain. But this does not solve the current problem that we spoof others. So to stop spoofing is the first thing to do.

**Comment by hanazuki** [comment] 2021-06-01 04:06
On the SPF record:

If we decide to send Redmine notifications from `notification@ruby-lang.org` via SendGrid, we have to add the SPF domain name provided by SendGrid to `ruby-lang.org`'s TXT record.
Manual is at: <https://sendgrid.com/docs/ui/account-and-settings/spf-records/>

For the record, the current configuration is:
```console
% dig TXT ruby-lang.org

; <<>> DiG 9.16.15-Debian <<>> TXT ruby-lang.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 63339
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;ruby-lang.org.                 IN      TXT

;; ANSWER SECTION:
ruby-lang.org.          158     IN      TXT     "_globalsign-domain-verification=6GywlC8PVV6mLfL6ToMeVqCDeqFk9IDu2uEqmYPqx3"
ruby-lang.org.          158     IN      TXT     "v=spf1 +ip4:210.251.121.208/28 +ip4:221.186.184.64/28 include:_spf.google.com ~all"

;; Query time: 0 msec
;; SERVER: 10.64.0.53#53(10.64.0.53)
;; WHEN: Tue Jun 01 04:05:18 UTC 2021
;; MSG SIZE  rcvd: 224
```

**Closed** 2021-08-16 02:44 UTC
